version: '3.7'

services:
  service-a:
    image: garystafford/go-srv-a:1.0.0
    networks:
      - golang-demo
    ports:
      - 8100:8000
  service-b:
    image: garystafford/go-srv-b:1.0.0
    networks:
      - golang-demo
  service-c:
    image: garystafford/go-srv-c:1.0.0
    networks:
      - golang-demo
    environment:
      MONGO_CONN: 'mongodb://mongodb:27017/service-c'
  service-d:
    image: garystafford/go-srv-d:1.0.0
    networks:
      - golang-demo
    environment:
      RABBITMQ_CONN: 'amqp://guest:guest@rabbitmq:5672/'
  service-e:
    image: garystafford/go-srv-e:1.0.0
    networks:
      - golang-demo
  service-f:
    image: garystafford/go-srv-f:1.0.0
    networks:
      - golang-demo
    environment:
      RABBITMQ_CONN: 'amqp://guest:guest@rabbitmq:5672/'
      MONGO_CONN: 'mongodb://mongodb:27017/service-f'
  service-g:
    image: garystafford/go-srv-g:1.0.0
    networks:
      - golang-demo
    environment:
      MONGO_CONN: 'mongodb://mongodb:27017/service-g'
  service-h:
    image: garystafford/go-srv-h:1.0.0
    networks:
      - golang-demo
    environment:
      MONGO_CONN: 'mongodb://mongodb:27017/service-h'
  mongodb:
    image: mongo:latest
    networks:
      - golang-demo
    ports:
      - 27017:27017
    command: --smallfiles
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - golang-demo

networks:
  golang-demo:
    external: true

volumes:
  data: {}
