apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - name: http
    port: 27017
  selector:
    app: mongodb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: mongodb
        image: mongodb:latest
        command: ["--smallfiles"]
        resources:
          requests:
            memory: "500M"
            cpu: "100m"
          limits:
            memory: "1000M"
            cpu: "500m"
        ports:
        - containerPort: 27017
        imagePullPolicy: IfNotPresent
