apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
    component: database
    version: "1.0.0"
spec:
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
  selector:
    name: mongodb
    component: database
    version: "1.0.0"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    name: mongodb
    component: database
    version: "1.0.0"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: mongodb
      component: database
      version: "1.0.0"
  template:
    metadata:
      labels:
        name: mongodb
        component: database
        version: "1.0.0"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: mongodb
        image: registry.hub.docker.com/library/mongo:latest
        # command: ["--smallfiles"]
        # resources:
        #   requests:
        #     memory: "500M"
        #     cpu: "100m"
        #   limits:
        #     memory: "1000M"
        #     cpu: "500m"
        ports:
        - containerPort: 27017
        imagePullPolicy: IfNotPresent
