apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - name: http
    port: 5672
  selector:
    app: rabbitmq
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        resources:
          requests:
            memory: "100M"
            cpu: "100m"
          limits:
            memory: "250M"
            cpu: "250m"
        ports:
        - containerPort: 5672
        imagePullPolicy: IfNotPresent
