apiVersion: v1
kind: Service
metadata:
  name: service-g
  labels:
    app: service-g
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: service-g
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-g
  labels:
    app: service-g
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service-g
  template:
    metadata:
      labels:
        app: service-g
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: service-g
        image: registry.hub.docker.com/garystafford/go-srv-g:1.0.0
        resources:
        # requests:
        #   memory: 100M
        #   cpu: 100m
        # limits:
        #   memory: 250M
        #   cpu: 250m
        env:
        - name: MONGO_CONN
          valueFrom:
            configMapKeyRef:
              name: go-srv-config
              key: mongodb.conn
        - name: RABBITMQ_CONN
          valueFrom:
            configMapKeyRef:
              name: go-srv-config
              key: rabbitmq.conn
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent