apiVersion: v1
kind: Service
metadata:
  name: service-d
  labels:
    name: service-d
    component: service
    version: "1.0.0"
spec:
  ports:
  - name: http
    port: 8000
  selector:
    name: service-d
    component: service
    version: "1.0.0"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-d
  labels:
    name: service-d
    component: service
    version: "1.0.0"
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: service-d
      component: service
      version: "1.0.0"
  template:
    metadata:
      labels:
        name: service-d
        component: service
        version: "1.0.0"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: service-d
        image: registry.hub.docker.com/garystafford/go-srv-d:1.0.0
        resources:
        # requests:
        #   memory: 100M
        #   cpu: 100m
        # limits:
        #   memory: 250M
        #   cpu: 250m
        env:
        - name: MONGO_CONN
          valueFrom:
            configMapKeyRef:
              name: go-srv-config
              key: mongodb.conn
        - name: RABBITMQ_CONN
          valueFrom:
            configMapKeyRef:
              name: go-srv-config
              key: rabbitmq.conn
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent
