apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: service-a
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: service-a
        image: garystafford/go-srv-a:1.0.0
        resources:
          requests:
            memory: "100M"
            cpu: "100m"
          limits:
            memory: "250M"
            cpu: "250m"
        env:
        - name: MONGO_CONN
          valueFrom:
            configMapKeyRef:
              name: go-srv-config
              key: mongo.conn
        - name: RABBITMQ_CONN
          valueFrom:
            configMapKeyRef:
              name: go-srv-config
              key: rabbitmq.conn
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
