apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: go-srv-demo-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: angular-ui
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: angular-ui-demo-dev
spec:
  hosts:
  - ui.example-api.com
  gateways:
  - go-srv-demo-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: angular-ui.dev.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-a-demo-dev
spec:
  hosts:
  - api.example-api.com
  gateways:
  - go-srv-demo-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8000
        host: service-a.dev.svc.cluster.local
